// <auto-generated />
namespace CarDealer.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addFeatureField2Car : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addFeatureField2Car));
        
        string IMigrationMetadata.Id
        {
            get { return "201804210249030_addFeatureField2Car"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
